language: node_js
os: linux
node_js:
- '9'
script: echo "Running jobs Install, Build & Test against $(node -v) ..."
jobs:
  include:
  - stage: Install
    script:
    - echo "Installing needed modules"
    - npm install
  - stage: Build
    script:
    - echo "Running build script ..."
    - npm run-script build
  - stage: Test
    script:
    - echo "Testing branch..." $TRAVIS_BRANCH
    - npm test
  - stage: Deploy
    branch:
      only: master
    if: "(type = push AND repo = elsevierlabs-os/react-logic-switch)"
    script:
    - echo "Deploying to NPM:" $TRAVIS_BRANCH
    - npm prerelease
    deploy:
      edge: true
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      cleanup: true